main: com.jrooke.DeathSwap.Plugin
name: DeathSwap
version: 1.0
api-version: 1.13
author: jrooke
commands:
   startds:
      description: Starts death swap
   stopds:
      description: Stops death swap
   skipds:
      description: Sets the time remaining to 20 seconds
      