main: com.jrooke.DeathSwap.Plugin
name: DeathSwap
version: 1.3
api-version: 1.13
author: jrooke
commands:
   startDs:
      description: Starts death swap
   stopDs:
      description: Stops death swap
   skipDs:
      description: Skips to the last 10 seconds
   setDsRoundTime:
      description: Sets the round time for the next game